### ISSUE TITLE
 If instr[14:12]=3’b111”, rd=M[rs1+rs2]. This instruction code is not defined in the RISC-V spec.

### ISSUE THREAD

**Issue by pearson78** [lowRISC/ibex#4] opened 2018-04-13 15:29 UTC
Please refer the line 289-307 in the RTL file “zeroriscy_decoder.sv”. If instr[14:12]=3’b111”, rd=M[rs1+rs2]. This instruction code is not defined in the RISC-V spec.

**Comment by imphil** [comment] 2019-05-16 16:37
This is referring to reg-reg loads as shown in this older snippet of the file:

https://github.com/lowRISC/ibex/blob/f7c2b6427045701706308f3a07b4848d3dc4e5b4/zeroriscy_decoder.sv#L289-L307

Duplicate of #25

**Closed by imphil** 2019-05-16 16:37 UTC
Labels: Type:Bug
