### ISSUE TITLE
ERROR while compiling assembler programs

### ISSUE THREAD

**Issue by Evgenii666** [lowRISC/ibex#661] opened 2020-03-06 12:32 UTC
Hello, I got the exact error that was described in Issue: https://github.com/lowRISC/ibex/pull/657.

After updating the repository, I run the make file and get the following error:

```
out/seed-24236/instr_gen/asm_tests/riscv_csr_test_0.S:526: Error: illegal operands li x2,0x0x8ffffffc 

out/seed-24236/instr_gen/asm_tests/riscv_csr_test_0.S:533: Error: illegal operands li x2,0x0x8ffffffc
```

**Comment by GregAC** [comment] 2020-03-06 13:36
Thanks for raising this @Evgenii666 what's happened here is one bug (which was this issue but caused by a missing '0x') has been fixed in two different places (leading to two '0x's). I'll open a PR to fix.

**Closed** 2020-03-06 13:55 UTC
