### ISSUE TITLE
Single Step does not work, if BRANCHPREDICTOR=1.

### ISSUE THREAD

**Issue by Sarafim** [lowRISC/ibex#1206] opened 2020-12-01 10:08 UTC
Hi, 
could you please check whether single step works, if BRANCHPREDICTOR=1.
It seems like depc_en is set to early, and that is why depc_q doesn't change its value.

I am asking, because on my side it works only if  BRANCHPREDICTOR=0.

**Comment by GregAC** [comment] 2020-12-01 10:32
It's certainly possible it's broken currently. The config with branch prediction enabled has seen the least testing out of all of the configs.

Do you observe single stepping failing always or only in certain scenarios?

**Comment by Sarafim** [comment] 2020-12-01 10:37
I can't say that I have tried lot of scenarios, but I see it always

**Comment by GregAC** [comment] 2020-12-01 10:58
When you say 'does not work' could you describe in more detail what you're actually seeing? Preferably with a waveform included.

**Comment by Sarafim** [comment] 2020-12-01 11:59
I mean that the depc_q does not change its value after the step
Correct behavior:
![image](https://user-images.githubusercontent.com/17382041/100737678-22d36380-33dd-11eb-809c-dda74a33f092.png)
Wrong behavior:
![image](https://user-images.githubusercontent.com/17382041/100737868-6cbc4980-33dd-11eb-9903-588a37309565.png)

**Comment by vogelpi** [comment] 2021-04-13 08:29
Hi @Sarafim ,
it has been a while but thanks for sharing the waveforms. Looking at them and the RTL code it's still not obvious what exactly causes the problem. When single stepping, the value saved into `depc` is always the PC in IF - independent whether the branch predictor is there or not. What changes with the branch predictor is that the PC in IF can either come from the skid buffer or the prefetch buffer.

To understand whether the problem is in the skid buffer or the prefetch buffer, some more insight into the test case would be needed. For example: What instructions are actually executed? Are you single stepping over branch instructions?

It would be very helpful if you could share a VCD file together with the disassembly. As @GregAC noted it is very well possible that there are issues around the branch predictor as its not as well tested as other configurations. But we would be interested to solve the issue.

**Comment by rswarbrick** [comment] 2021-05-21 10:44
Hi there! I'm closing this issue because it has been silent for a while and the development team doesn't have enough information to make any progress. @Sarafim: if you manage to reproduce this and can share a trace and disassembly as @vogelpi suggested, please feel free to re-open.

**Closed by rswarbrick** 2021-05-21 10:44 UTC
Labels: Component:RTL, Type:Bug
