### ISSUE TITLE
spike cosim.cc

### ISSUE THREAD

**Issue by shanshuixiangyi** [lowRISC/ibex#1998] opened 2023-03-14 07:00 UTC
I met a problem, Can anyone help me ?
```
test_jiahua/ibex/dv/cosim/spike_cosim.cc:941:46: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
/test_jiahua/test2/newspike/include/riscv/processor.h:225:12: warning: 'int cto(reg_t)' defined but not used [-Wunused-function]
"/test_jiahua/ibex/dv/cosim/spike_cosim.cc", line 66: error: class
          "processor_t" has no member "enable_log_commits"
      processor->enable_log_commits();
                 ^

"/test_jiahua/ibex/dv/cosim/spike_cosim.cc", line 231: error: class "state_t"
          has no member "last_inst_pc"
    if (processor->get_state()->last_inst_pc == PC_INVALID) {
                                ^

"/test_jiahua/ibex/dv/cosim/spike_cosim.cc", line 245: error: class "state_t"
          has no member "last_inst_pc"
        if (processor->get_state()->last_inst_pc == PC_INVALID) {
                                    ^

"/test_jiahua/ibex/dv/cosim/spike_cosim.cc", line 322: error: class "state_t"
          has no member "last_inst_pc"
    if ((processor->get_state()->last_inst_pc & 0xffffffff) != dut_pc) {
                                 ^

"/test_jiahua/ibex/dv/cosim/spike_cosim.cc", line 326: error: class "state_t"
          has no member "last_inst_pc"
              << std::hex << processor->get_state()->last_inst_pc;
                                                     ^



xmsc: Error executing: $CDSROOT/tools/cdsgcc/gcc/6.3/bin/g++ -DNCSC -DCADENCE  -DLNX86 -D_GLIBCXX_USE_CXX11_ABI=0 -I$CDSROOT/tools/systemc/include_pch/64bit -o $TESTDIR/out/build/tb/xcelium.d/run.lnx8664.20.09.d/xmsc_run/xmsc_obj/spike_cosim_0.o -I/test_jiahua/ibex/dv/cosim -I/test_jiahua/test2/newspike/include -I/test_jiahua/test2/newspike/include/softfloat -I$CDSROOT/tools/include -I$CDSROOT/tools/inca/include -DXMSC -DNCSC -I$CDSROOT/tools/systemc/include_pch -I$CDSROOT/tools/tbsc/include -I$CDSROOT/tools/vic/include -I$CDSROOT/tools/methodology/OVM/CDNS-2.1.2/sc/src -I$CDSROOT/tools/methodology/UVM/CDNS-1.2/sc/sc -I$CDSROOT/tools/methodology/UVM/CDNS-1.2/ml/sc -I$CDSROOT/tools/systemc/include/cci -I$CDSROOT/tools/systemc/include/factory -I$CDSROOT/tools/systemc/include/tlm2 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -c -x c++  -Wall /test_jiahua/ibex/dv/cosim/spike_cosim.cc
xmsc_run: *E,TBBLDF: Failed to generate object /test_jiahua/ibex/dv/uvm/core_ibex/out/build/tb/xcelium.d/run.lnx8664.20.09.d/xmsc_run/xmsc_obj/spike_cosim_0.o

xrun: *E,CCERR: Error during cc compilation (status 1), exiting.
```

**Comment by rswarbrick** [comment] 2023-05-19 11:29
Hi there, and sorry for the slow response. I suspect the problem is that you're not using the lowRISC flavour of Spike. For information about what you need, see the documentation in `cosim.rst`.

I'm closing this issue because I think the problem is just in following the documentation. Please feel free to re-open if I'm wrong.

**Closed by rswarbrick** 2023-05-19 11:29 UTC
Labels: Type:Question
