### ISSUE TITLE
Ibex simple system fails to simulate with verilator (segmentation fault)

### ISSUE THREAD

**Issue by ganoam** [lowRISC/ibex#1352] opened 2021-05-03 10:38 UTC
Ibex simple system verilator simulation fails with segmentation fault. I have tracked down the fault to the function `DpiMemUtil::RegisterMemoryArea`, and I believe the fault occurs somewhere here:
https://github.com/lowRISC/ibex/blob/8ef06de73daa7c22400f0e617088aeea06a2601c/vendor/lowrisc_ip/dv/verilator/cpp/dpi_memutil.cc#L329-L338

Unfortunately I lack the context to fix it....

I am simulating with verilator v. 4.200.
How to reproduce:
```
fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ibex:ibex_simple_system # build simulator
make -C examples/sw/simple_system/hello_test/ # build elf
./build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/Vibex_simple_system --meminit=ram,examples/sw/simple_system/hello_test/hello_test.elf # Run sim

**Comment by rswarbrick** [comment] 2021-05-17 08:50
Ok, I can't reproduce this and I don't think anyone else is seeing it either. Let's close this issue, but please feel free to reopen with more information if you crash into anything like this again.

**Comment by mrdiogodias** [comment] 2021-05-19 09:42
Hello,
I'm facing the same problem. I have verilator 4.028 and I just followed the commands on the readme of the simple_system directory.

Error:
`[1]    49657 segmentation fault (core dumped)  ./build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/Vibex_simple_system `

**Comment by imphil** [comment] 2021-05-19 09:52
Can you:
* Try with the latest version of Verilator (4.202)
* Run under gdb by prefixing `gdb --args` to the command you were trying to run (e.g. `gdb --args ./build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/Vibex_simple_system`). Type `r` (and ENTER) after GDB starts up, and once the program crashes, type `bt` (and ENTER) to get a backtrace. Please post the backtrace here.

**Comment by mrdiogodias** [comment] 2021-05-19 12:53
It worked with the latest version of verilator (4.202).
Sorry for my laziness, I should have tried it first.

**Comment by rswarbrick** [comment] 2021-05-19 12:58
That's helpful, thanks. If you can reproduce with an older Verilator, could you give us a backtrace? It might be there's still a bug in our code that's only triggered with certain setups. It would be nice to track down what's going on.

**Comment by rswarbrick** [comment] 2021-05-19 13:15
Thanks for the bug report. I've just pushed up the PR above which will fix it in OpenTitan. Once that's merged, I'll vendor the change back into Ibex.

**Closed** 2021-05-25 14:14 UTC
Labels: Type:Bug
