### ISSUE TITLE
Addr && be not stable during read req

### ISSUE THREAD

**Issue by elchanan18** [lowRISC/ibex#121] opened 2019-07-04 12:08 UTC
I'm seeing data_addr_o and data_be_o change, while data_req_o is high, and data_gnt_i has not been received.
Is it possible I'm misreading the spec?  (or that there are illegal things I might have in the environment which could cause this?)
Thank you.

![ibex_req_gnt_stable](https://user-images.githubusercontent.com/52534675/60665504-49e6d800-9e6d-11e9-8b46-7a1165555930.JPG)

**Comment by vogelpi** [comment] 2019-07-04 12:24
Hi @elchanan18 ,
thanks for reporting this issue.

The address changing in Cycle 5 with request high but without getting a grant does indeed not look good. Would you mind to provide some more details? Ideally a VCD file for the whole processor? This would help me to look into it.

Best regards,
Pirmin

**Comment by elchanan18** [comment] 2019-07-04 12:31
Hi Pirmin,
Thanks for the quick response.
Is it possible to attach a VCD file to this thread?  (about 75K)

**Comment by vogelpi** [comment] 2019-07-04 12:33
Yes, that should work. You can just attach it here.

**Comment by elchanan18** [comment] 2019-07-04 12:37
I had to rename the file type to .txt.
It would let me drag a .vcd

[addr_not_stable.txt](https://github.com/lowRISC/ibex/files/3359295/addr_not_stable.txt)

**Comment by vogelpi** [comment] 2019-07-04 13:22
Thanks for uploading the VCD (to get around the restriction regarding the name and save some space, you can also do a zip).

I had a look on the VCD. The problem is complicated. The core tries to do a non-aligned load. Non-aligned loads are split into two consecutive aligned loads. The first of these two loads fails (the bus returns an error in `data_err_i`). To store the faulting address in the `mtval` CSR, the LSU cannot store the address incoming for the second load. This results in the output address being changed despite not getting a grant. This could be solved by just aborting the LSU operation on the error.

What makes the situation more complicated is that in your case, while the LSU informs the controller (`ibex_controller.sv`) about the load error, the controller is not sensitive to this information as it is in another state (`DBG_TAKEN_ID` instead of `DECODE`). This is part of a bigger problem we currently have in the controller. There are other issues open because of the same thing. I am working on it.

Best regards,
Pirmin

**Comment by vogelpi** [comment] 2019-07-05 14:58
Hi @elchanan18 

I have reworked the faulty controller FSM to solve the second part of the problem you reported. However, this fix depends on other changes currently under review here #120 . Thus I did not create a PR for these latest changes.

Nevertheless, the changes are available on my development branch here: https://github.com/vogelpi/ibex/tree/vogelpi-dev

Would you mind to checkout this branch and give me some feedback if it properly works in your setup?
Best regards and have a nice weekend,
Pirmin

**Comment by elchanan18** [comment] 2019-07-05 15:13
Here's what I'm getting now.

![addr_stable](https://user-images.githubusercontent.com/52534675/60731572-90613300-9f50-11e9-9042-302926a2aff2.JPG)

**Comment by elchanan18** [comment] 2019-07-05 15:16
[addr_stable.zip](https://github.com/lowRISC/ibex/files/3363257/addr_stable.zip)

**Comment by vogelpi** [comment] 2019-07-05 15:42
Thanks for getting back, I obviously had made an error before. Fixed that now. You can retry, be careful though, I did a force push to my dev branch.

**Comment by elchanan18** [comment] 2019-07-05 16:09
I think I got the new code.

![Screenshot from 2019-07-05 19-06-26](https://user-images.githubusercontent.com/52534675/60734308-349aa800-9f58-11e9-8dff-49a26ab9c0bc.png)
[addr_stable2.zip](https://github.com/lowRISC/ibex/files/3363431/addr_stable2.zip)

**Comment by vogelpi** [comment] 2019-07-05 17:08
Thanks @elchanan18 !
I analyzed the waves. Behavior of the processor looks good now.

1. It jumps into debug mode at the beginning and then reads a fence instruction with bits [14:12] != 000.
2. This is illegal. The core thus raises an exception and jumps into the debug-mode exception handler (at address 0x1A110808).
3. The first instruction in there is a LOAD, which returns an error from the bus.
4. This again raises an exception, the core jumps back to the debug-mode exception handler (again at address 0x1A110808).
5. The first instruction it gets now from memory is a JAL. This is strange. As the IF stage reads at the same address as before but gets a different value from memory. Is this to be expected in your setup?
6. Anyway, it computes the correct target and stores the PC in a register 1.
7. The core then jumps to the computed target.

Is it expected in your test setup that the memory returns a different value in 5 and 3? If not, this could mean we have a new bug in the IF stage. Please let me know.

Best regards,
Pirmin

**Comment by elchanan18** [comment] 2019-07-06 20:09
Hi.  No, I'm using Formal, and not restricting reads to return the same data.
Are you saying that you made another fix, or that what I'm seeing now is correct?
If the latter, is it OK for addr and be to change w/o gnt ?

**Comment by imphil** [comment] 2019-07-06 20:14
>  If the latter, is it OK for addr and be to change w/o gnt ?

yes, please see https://ibex-core.readthedocs.io/en/latest/instruction_fetch.html

"The IF protocol differs from the LSU protocol in that the address can change while the request is valid (instr_req_o is high)."

**Comment by elchanan18** [comment] 2019-07-06 20:31
Right.  For instr it would be OK.  But we're looking at the LSU data interface.

**Comment by vogelpi** [comment] 2019-07-08 09:27
Hi @elchanan18,
yep that is still wrong. I did not see it on Friday sorry. But thanks for getting back. I am working on a fix for this now.

**Comment by vogelpi** [comment] 2019-07-08 16:07
@elchanan18 ,
I fixed the problem. The problem was that while the LSU aborted the first failing misaligned transaction, some internal control logic did not get cleared. This prevented the next misaligned transaction to be recognized as such.

I again force-pushed to my dev branch in case you want to retry execution.
Best,
Pirmin

**Comment by elchanan18** [comment] 2019-07-08 16:47
Hi,

Now I'm getting an issue with byte enables.

![Screenshot from 2019-07-08 19-45-14](https://user-images.githubusercontent.com/52534675/60827488-fea82e80-a1b8-11e9-90ee-b6820e538a4d.png)
[addr_stable3.zip](https://github.com/lowRISC/ibex/files/3369382/addr_stable3.zip)

**Comment by vogelpi** [comment] 2019-07-08 17:11
Thanks @elchanan18 , also this should be fixed now.

**Comment by elchanan18** [comment] 2019-07-08 19:13
This looks better.  I've been running Formal for over an hour, and it hasn't found a counter-example yet.  (the other failures popped up in a few seconds)

**Comment by elchanan18** [comment] 2019-07-08 20:58
Confirmed.  After 2 hours, Formal says it will never happen.

**Comment by vogelpi** [comment] 2019-07-09 09:12
Great! Thanks a lot @elchanan18 , your help is much appreciated!

I consider this issue solved, but I'll keep the issue open until the bug fixes are merged into master.

**Closed** 2019-07-09 14:39 UTC
Labels: Component:RTL, Type:Bug
