### ISSUE TITLE
Running "make" in verification failed with spike errors. 

### ISSUE THREAD

**Issue by lotharelvin** [lowRISC/ibex#1652] opened 2022-05-12 02:41 UTC
## Observed Behavior
When I run "make" in the verification folder like:
`[oyykyook@mics-eda core_ibex]$ make
make: *** [Makefile:289: out/run/riscv_arithmetic_basic_test.28990/spike.log] Error 1
`
It reports a spike error.
`make: *** [Makefile:289: out/run/riscv_arithmetic_basic_test.28990/spike.log] Error 1`

The contents of the log are:
**/home/oyykyook/riscv/bin/spike: /lib64/libstdc++.so.6: version \`GLIBCXX_3.4.20' not found (required by /home/oyykyook/riscv/bin/spike)
/home/oyykyook/riscv/bin/spike: /lib64/libstdc++.so.6: version \`CXXABI_1.3.8' not found (required by /home/oyykyook/riscv/bin/spike)
/home/oyykyook/riscv/bin/spike: /lib64/libstdc++.so.6: version \`GLIBCXX_3.4.21' not found (required by /home/oyykyook/riscv/bin/spike)**

## Steps to reproduce the issue

Simply run "make" in ibex/dv/uvm/core_ibex folder.
## My Environment

I have install the spike version provided by ibex and I can successfully run riscv-dv tests in ibex/vendor/google_riscv-dv folder as follows:
[oyykyook@mics-eda google_riscv-dv]$ python run.py --test riscv_arithmetic_basic_test
Thu, 12 May 2022 22:29:23 INFO     Creating output directory: out_2022-05-12
Thu, 12 May 2022 22:29:23 INFO     Processing regression test list : /home/oyykyook/ibex/vendor/google_riscv-dv/target/rv32imc/testlist.yaml, test: riscv_arithmetic_basic_test
Thu, 12 May 2022 22:29:23 INFO     Processing regression test list : /home/oyykyook/ibex/vendor/google_riscv-dv/yaml/base_testlist.yaml, test: riscv_arithmetic_basic_test
Thu, 12 May 2022 22:29:23 INFO     Found matched tests: riscv_arithmetic_basic_test, iterations:2
Thu, 12 May 2022 22:29:23 INFO     Processing simulator setup file : /home/oyykyook/ibex/vendor/google_riscv-dv/yaml/simulator.yaml
Thu, 12 May 2022 22:29:23 INFO     Found matching simulator: vcs
Thu, 12 May 2022 22:29:23 INFO     Building RISC-V instruction generator
Thu, 12 May 2022 22:29:39 INFO     Running RISC-V instruction generator
Thu, 12 May 2022 22:29:39 INFO     Generating 2 riscv_arithmetic_basic_test
Thu, 12 May 2022 22:29:39 INFO     Running riscv_arithmetic_basic_test with 1 batches
Thu, 12 May 2022 22:29:39 INFO     Running riscv_arithmetic_basic_test, batch 1/1, test_cnt:2
Thu, 12 May 2022 22:29:41 INFO     Compiling out_2022-05-12/asm_test/riscv_arithmetic_basic_test_0.S
Thu, 12 May 2022 22:29:42 INFO     Converting to out_2022-05-12/asm_test/riscv_arithmetic_basic_test_0.bin
Thu, 12 May 2022 22:29:42 INFO     Compiling out_2022-05-12/asm_test/riscv_arithmetic_basic_test_1.S
Thu, 12 May 2022 22:29:42 INFO     Converting to out_2022-05-12/asm_test/riscv_arithmetic_basic_test_1.bin
Thu, 12 May 2022 22:29:42 INFO     Processing ISS setup file : /home/oyykyook/ibex/vendor/google_riscv-dv/yaml/iss.yaml
Thu, 12 May 2022 22:29:42 INFO     Found matching ISS: spike
Thu, 12 May 2022 22:29:42 INFO     spike sim log dir: out_2022-05-12/spike_sim
Thu, 12 May 2022 22:29:42 INFO     Running spike sim: out_2022-05-12/asm_test/riscv_arithmetic_basic_test_0.o
Thu, 12 May 2022 22:29:42 INFO     Running spike sim: out_2022-05-12/asm_test/riscv_arithmetic_basic_test_1.o

**So I guess the spike is installed correctly.**
**EDA tool and version:**

**Operating system:**

CentOS Linux release 7.9.2009 (Core).

**Version of the Ibex source code:**

361f2ddedf0ea95dbdfeda1cd1c510b83fb323f4
I did not make any changes to the code.

Thanks!

**Comment by rswarbrick** [comment] 2022-05-12 08:45
This means that you have downloaded a Spike binary that requires a newer libc than you have installed on your system. That's not going to work! Also, you have to build your own Spike for Ibex testing: see https://ibex-core.readthedocs.io/en/latest/03_reference/verification.html for the details.

Closing this now since it's caused by a problem with your setup. Let us know if you find any other problems once you have a working Spike installation.

**Closed by rswarbrick** 2022-05-12 08:45 UTC
Labels: Type:Bug
