### ISSUE TITLE
Parameter of type 'string' is not supported by Cadence Genus

### ISSUE THREAD

**Issue by pbing** [lowRISC/ibex#429] opened 2019-10-26 10:39 UTC
The new parameter `MultiplierImplementation` is not synthesizable with Cadence Genus.

```
Error   : Unsupported declaration. [VLOGPT-32] [read_hdl]
        : String type in file '../../ibex/rtl/ibex_ex_block.sv' on line 13, column 20.
        : The following declarations are not supported for synthesis:
    - tri0
    - tri1
    - event
    - class
    - chandle
    - SV string type
    - associative array.
    parameter string MultiplierImplementation = "fast"
```

Maybe '0 / 1' instead of '"slow" / "fast"' could be considered instead?

**Comment by imphil** [comment] 2019-10-26 13:32
Can you please give it a try without the "string" type annotation? I.e. just "parameter MultiplierImplementation"?

**Comment by pbing** [comment] 2019-10-26 14:03
This work around could be synthezised.

> Am 26.10.2019 um 15:32 schrieb Philipp Wagner <notifications@github.com>:
> 
> Can you please give it a try without the "string" type annotation? I.e. just "parameter MultiplierImplementation"?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

— 
Bernd

**Comment by pcotret** [comment] 2019-10-28 15:10
I was playing with @GregAC [example](https://github.com/lowRISC/ibex/tree/master/examples/fpga/artya7-100) for the Arty board.

Got the same problem with Vivado 2018.2 on two files:
- ibex_core.sv
- ibex_ex_block.sv

Synthesis is OK without the **string** type annotation.

**Comment by imphil** [comment] 2019-10-28 16:51
Would you mind opening a PR removing the string annotation?

**Comment by pcotret** [comment] 2019-10-28 16:56
Sure, will do it a bit later.

**Comment by vogelpi** [comment] 2019-10-31 17:53
I am closing this issue now. lowRISC/ibex#430 has been closed but lowRISC/ibex#431 got merged instead. The issue is fixed.

**Closed by vogelpi** 2019-10-31 17:53 UTC
